/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconMusic: typeof import('./src/components/icons/IconMusic.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import("@varlet/ui")["_ButtonComponent"]
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarImagePreview: typeof import('@varlet/ui')['_ImagePreviewComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    WeddingBlock: typeof import('./src/components/WeddingBlock.vue')['default']
    WeddingHome: typeof import('./src/components/WeddingHome.vue')['default']
    WeddingInviation: typeof import('./src/components/WeddingInviation.vue')['default']
    WeddingMap: typeof import('./src/components/WeddingMap.vue')['default']
    WeddingPictures: typeof import('./src/components/WeddingPictures.vue')['default']
    WeddingProfile: typeof import('./src/components/WeddingProfile.vue')['default']
  }
}
