/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import("./src/components/icons/IconEn copy.vue")["default"]
    IconAccountGroup: typeof import('./src/components/icons/iconAccountGroup.vue')['default']
    IconCalendar: typeof import('./src/components/icons/IconCalendar.vue')['default']
    IconCash: typeof import('./src/components/icons/iconCash.vue')['default']
    IconCity: typeof import('./src/components/icons/IconCity.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconEn: typeof import('./src/components/icons/IconEn.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconPhone: typeof import('./src/components/icons/iconPhone.vue')['default']
    IconPost: typeof import('./src/components/icons/IconPost.vue')['default']
    IconSchool: typeof import('./src/components/icons/IconSchool.vue')['default']
    IconTencent: typeof import('./src/components/icons/IconTencent.vue')['default']
    IconWechat: typeof import('./src/components/icons/iconWechat.vue')['default']
    IconZh: typeof import('./src/components/icons/IconZh.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarIcon: typeof import("@varlet/ui")["_IconComponent"]
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarProgress: typeof import("@varlet/ui")["_ProgressComponent"]
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSpace: typeof import("@varlet/ui")["_SpaceComponent"]
    VarStep: typeof import("@varlet/ui")["_StepComponent"]
    VarSteps: typeof import("@varlet/ui")["_StepsComponent"]
    VarSwipe: typeof import("@varlet/ui")["_SwipeComponent"]
    VarSwipeItem: typeof import("@varlet/ui")["_SwipeItemComponent"]
    WeddingBlock: typeof import('./src/components/WeddingBlock.vue')['default']
    WeddingHome: typeof import('./src/components/WeddingHome.vue')['default']
    WeddingMap: typeof import('./src/components/WeddingMap.vue')['default']
    WeddingPictures: typeof import('./src/components/WeddingPictures.vue')['default']
    WeddingProfile: typeof import('./src/components/WeddingProfile.vue')['default']
  }
}
